@startuml
' https://plantuml.com/fr/class-diagram
Object Scope {
id
name
}

Object Classroom {
id
name
}

Object Response {
id
proposition
feedback
value
}

Object Rating {
id
value
}

Object Question{
id
name
sentence
dateCrea
designerName
codesignerNames
}

Object User{
id
userName
email
password
valide
}

Object Role {
id
name
}

User "*" - "*" Role:"\t\t\t\t"

@enduml
